# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory
WORKDIR /usr/src/app

# Copy the current directory contents into the container
COPY . .

# Command to run the script
CMD ["python", "main.py"]
